### ISSUE TITLE
Mater IQTools refresh error

### ISSUE THREAD

**Issue by mkaburu** [chap-uzima/IQTools#39] opened 2018-06-22 05:31 UTC
@chris-githu getting this error when refreshing Mater 4.1 DB
![iqmater](https://user-images.githubusercontent.com/31726479/41759329-8fb1589c-75f6-11e8-8333-f49f88e342b2.JPG)
Link to DB:https://drive.google.com/file/d/1uDMrFAkKrdO1O4jQbJEF5S6tF0cWA1NN/view?usp=sharing_eil&ts=5b2ba2ff

**Comment by chris-githu** [comment] 2018-06-25 13:43
@mkaburu 
Please test this in v4.2.2-beta

**Comment by chris-githu** [comment] 2018-06-25 13:58
FYI @mkaburu 
This was caused by a Viral Load result documented as "less than 20" Please follow up with the site to determine why we still have text results. This should be either LDL or a numeric value.
Thanks.

**Comment by chris-githu** [comment] 2018-06-27 05:49
@mkaburu Please let me know if we can close this issue.
Thanks.

**Comment by mkaburu** [comment] 2018-06-27 07:07
@chris-githu yes we can close it

**Closed** 2018-06-27 07:30 UTC
